title: Oscar Adimi
description: I blog about Python, Machine Learning and AI.
author: Oscar Adimi
email: tuscar2001@gmail.com
#phone: 
github: https://github.com/tuscar2001
about: I am a Data Scientist
disqus_shortname: programming
#google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/tjamadar"
    - icon: fa-twitter
      link: "https://twitter.com/tmjam3011"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/tauseef-jamadar-5b577913/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/tuscar2001"

share:
  twitter_username: tmjam3011
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://tuscar2001.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
